### ISSUE TITLE
Bower package?

### ISSUE THREAD

**Issue by sualko** [strophe/strophejs-plugin-vcard#1]
I would like to use this plugin and also others as bower packages. Can I just add the desired bower file, or are there any other plans? I would also help to bump versions, if you tell me how this is handled in the strophe organization.

**Comment by sualko** [comment]
cc @jcbrand

**Comment by jcbrand** [comment]
Honest question, why do you still use bower? I find NPM much better and I don't see any need for Bower anymore.

For example, with bower, sometimes people change/delete tags, which means the package is no longer available. Also, with bower, you often don't get the dist files because bower doesn't link to an actual distribution of the package.

I also much more regularly had download issues with bower, much less so with NPM.

NPM functions more like a package manager (e.g. Pypi for Python, Luarocks for Lua, RubyGems for Ruby). When a package is uploaded, it will (usually) have the dist files generated and people can't willy-nilly remove packages once uploaded there.

That said, you're welcome to add .bowerrc files if that helps you. Concerning versioning, please make tags of versions and keep an up to date changelog, like with strophe.js: https://github.com/strophe/strophejs/blob/master/CHANGELOG.md

It's also nice when the changes are mentioned in the Github releases page: https://github.com/strophe/strophejs/releases

**Comment by sualko** [comment]
> why do you still use bower?

That's a good question. I think because I am used to it, but you are probably right. How does it work with packages/repos which where no npm package?

**Comment by jcbrand** [comment]
You can simply link to the Github (or public git) repo.

**Comment by sualko** [comment]
Thank you very much. I was not aware of this.
